### ISSUE TITLE
unit tests don't compile

### ISSUE THREAD

**Issue by GlenDC** [rivine/rivine#38]
There are currently quite a lot of unit tests that don't compile. I can only imagine that this is the result of heavy refactoring and the hard work done after the hard fork of Sia? I suppose this is not new to you, but I was wondering what to do with this? Should this be ignored for now, or should I help in fixing this?

**Comment by GlenDC** [comment]
Some of this is related to issue #37, and could be solved (partially) together.

**Comment by LeeSmet** [comment]
Added a wip on a separate branch:

- Fixed some tests which have just been renamed
- Placed a comment on tests which call removed/reworked methods with a link to the commit in which they have been removed

No effort has been done to fix failing unit tests, I guess that should be handled in separate issues

**Comment by robvanmieghem** [comment]
packages that are fine now( in the fix unit tests branch):
- build
- crypto
- encoding
- modules
- modules/gateway
- persist
- rivinec
- rivined
- sync
- types

still broken:
-api
- modules/blockcreator
- modules/consensus
- modules/explorer
- modules/transactionpool
- modules/wallet

**Comment by GlenDC** [comment]
Partly fixed by 9d4bb5a1ce661c144bbd60ea26555e35a8b2f689 (squashed merge result of PR #75).
